Major_groups={
'Computer Science':'Computer Science',                               
'Speech Language Pathology':'Speech Language Pathology',                  
'Economics':'Economics',                                   
'Chemistry':'Chemistry',                                       
'Physics':'Physics',                                         
'Mechanical Engineering':'Engineering',                          
'Electrical And Computer Engineering':'Engineering',   
'Statistics':'Mathematics',                                      
'Political Science':'Political Science',                               
'Chemical Engineering':'Engineering',                            
'Philosophy':'Philosophy',                                     
'Sociology':'Sociology',                                     
'( ECE ) Electrical And Computer Engineering':'Engineering', 
'Electrical Engineering':'Engineering',                         
'Data Science':'Computer Science',                                   
'Pure Mathematics':'Mathematics',                                
'Public Policy':'Public Policy',                                    
'Mathematics':'Mathematics ',                                     
'Materials Science And Engineering':'Engineering',               
'Biostatistics':'Medical',                                  
'English':'English',                                     
'CCDS Speech Language Pathology':'Speech Language Pathology',                  
'(Computer Science )':'Computer Science',                             
'Biomedical Engineering':'Engineering',                          
'Civil Engineering':'Engineering',                               
'Communication Sciences And Disorders':'Science',            
'Aerospace Engineering':'Engineering',                           
'Architecture':'Architecture',                                    
'History':'History',                                         
'Robotics':'Robotics',                                        
'Civil And Environmental Engineering':'Engineering',             
'(Computer Science':'Computer Science',                              
'(Pure) Mathematics':'Mathematics',                            
'"Physics"':'Physics',                                      
'CDDS Speech Language Pathology':'Speech Language Pathology',                   
'Epidemiology':'Medical',                            
'Clinical Psychology':'Psychology',                            
'Public Health':'Medical',                                    
'Speech Pathology':'Speech Language Pathology',                                   
'Public Administration':'Public Administration'}  